### ISSUE TITLE
Add continuous integration on OSX

### ISSUE THREAD

**Issue by jacebrowning** [malthe/macfsevents#32]
Travis CI is a good option for this.

Steps:

- [x] Grant Travis CI permissions
- [ ] Add a `.travis.yml` configured for Python and OSX
- [ ] Add a status badge

**Comment by jacebrowning** [comment]
@malthe Can you complete steps 1 and 2 on here for me?

https://docs.travis-ci.com/user/getting-started/#To-get-started-with-Travis-CI%3A

**Comment by jacebrowning** [comment]
I'll add a `.travis.yml` file in a pull request that will activate builds once those steps are complete.

**Comment by malthe** [comment]
That's done now.

**Comment by jacebrowning** [comment]
Thanks! How do you run your tests? `$ python setup.py build test`?

**Comment by malthe** [comment]
Yep, that's how I run, or ran them.
