### ISSUE TITLE
Add License File

### ISSUE THREAD

**Issue by pbronez** [malthe/macfsevents#38]
The README [says](https://github.com/malthe/macfsevents) that "[this software is] Made available as-is under the BSD License." but doesn't specify which BSD license applies. The Pypi metadata [specifies](https://pypi.python.org/pypi/MacFSEvents) the MIT license.

Could you add a LICENSE file with the text of your intended license? (I can do a pull request if you let me know which one you want)

I'm trying to package MacFSEvents for conda-forge, and the license issue is currently [a roadblock](https://github.com/conda-forge/staged-recipes/pull/4219#pullrequestreview-71038602)

**Comment by malthe** [comment]
Added in e99231e8382b6a6cbc769bfa17c44ea9c1a35c37.

Thanks.
